spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crayondb
    username: root
    password: mysql@macos
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow: 127.0.0.1,192.168.46.120
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.46.121
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
#### redis
  redis:
    host: localhost
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 8
        min-idle: 1
#### eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10