server:
  port: 9021

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: CRAYON-DATA-SERVICE
#  datasource:
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/crayonlogdb
#      username: root
#      password: root
#      stat-view-servlet:
#        enabled: true
#        url-pattern: "/druid/*"
#        # IP白名单(没有配置或者为空，则允许所有访问)
#        # allow: 127.0.0.1,192.168.46.120
#        # IP黑名单 (存在共同时，deny优先于allow)
#        # deny: 192.168.46.121
#        #  禁用HTML页面上的“Reset All”功能
#        reset-enable: false
#        # 登录名
#        login-username: admin
#        # 登录密码
#        login-password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


sharding:
  jdbc:
    datasource:
      names: crayonlogdb
      crayonlogdb:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/crayonlogdb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
        username: root
        password: root
#      ds1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/ds1
#        username: root
#        password: root
    config:
      sharding:
        tables:
          crayon_log:
            actual-data-nodes: crayonlogdb.crayon_log$->{0..4}
            table-strategy:
              inline:
                sharding-column: log_id
                algorithm-expression: crayon_log$->{log_id % 5}
            key-generator-column-name: log_id
        binding-tables: crayon_log
        default-database-strategy:
          none:
            any: none
        props:
          sql.show: true
#        broadcast-tables: t_config
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.crayon.pojo.po
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
