spring:
  redis:
    host: localhost
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 8
        min-idle: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/